version: '3.8'

services:
  # 后端API服务
  backend:
    build: ./backend
    container_name: housing-price-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/Data.csv:/app/Data.csv
      - ./backend/markov_model.h5:/app/markov_model.h5
    environment:
      - FLASK_ENV=production

  # 前端服务
  frontend:
    build: ./frontend
    container_name: housing-price-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped 