name: 部署到GitHub Pages

on:
  push:
    branches:
      - main  # 当代码推送到main分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: housing-price-dashboard/frontend/package-lock.json

      - name: 安装依赖
        run: npm ci
        working-directory: ./housing-price-dashboard/frontend

      - name: 构建应用
        run: npm run build -- --configuration production --base-href=/housing-price-dashboard/
        working-directory: ./housing-price-dashboard/frontend

      - name: 确保assets目录存在
        run: mkdir -p src/assets/github-pages
        working-directory: ./housing-price-dashboard/frontend

      - name: 复制404页面到构建目录
        run: cp src/assets/github-pages/404.html dist/housing-price-dashboard/
        working-directory: ./housing-price-dashboard/frontend

      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: housing-price-dashboard/frontend/dist/housing-price-dashboard  # 部署的文件夹
          branch: gh-pages  # 部署的目标分支 